### ISSUE TITLE
Android app crashed before check location permission

### ISSUE THREAD

**Issue by pnthach95** [zoontek/react-native-permissions#231]
### Describe your environment

* React-Native version 0.48.4
* Platform: Android
* Device: Nokia 5
* OS version: 8.0.0
* react-native-permissions version: 1.1.1
* Devtools: Android Studio version 3.0.0
* (buildToolsVersion: 25.0.3)

### How to repeat issue and example

My app crashes on first time run. If I manually check location permission, it run perfectly.

Here's logcat:
```
FATAL EXCEPTION: main
Process: com.ebikes, PID: 16752
java.lang.SecurityException: Client must have ACCESS_FINE_LOCATION permission to request PRIORITY_HIGH_ACCURACY locations.
  at android.os.Parcel.readException(Parcel.java:1942)
  at android.os.Parcel.readException(Parcel.java:1888)
  at com.google.android.gms.internal.zzed.zzb(Unknown Source:10)
  at com.google.android.gms.internal.zzcda.zza(Unknown Source:9)
  at com.google.android.gms.internal.zzcdd.zza(Unknown Source:40)
  at com.google.android.gms.internal.zzcdj.zza(Unknown Source:5)
  at com.google.android.gms.internal.zzccc.zza(Unknown Source:25)
  at com.google.android.gms.internal.zzbay.zzb(Unknown Source:0)
  at com.google.android.gms.internal.zzbca.zze(Unknown Source:68)
  at com.google.android.gms.internal.zzbcx.zze(Unknown Source:5)
  at com.google.android.gms.internal.zzbcp.zze(Unknown Source:147)
  at com.google.android.gms.internal.zzccb.requestLocationUpdates(Unknown Source:14)
  at com.timhagn.rngloc.LocationProvider.onConnected(LocationProvider.java:119)
  at com.google.android.gms.common.internal.zzac.zzn(Unknown Source:108)
  at com.google.android.gms.internal.zzbcp.zzm(Unknown Source:22)
  at com.google.android.gms.internal.zzbcd.zzpY(Unknown Source:89)
  at com.google.android.gms.internal.zzbcd.onConnected(Unknown Source:21)
  at com.google.android.gms.internal.zzbcx.onConnected(Unknown Source:7)
  at com.google.android.gms.internal.zzbbi.onConnected(Unknown Source:5)
  at com.google.android.gms.common.internal.zzaa.onConnected(Unknown Source:2)
  at com.google.android.gms.common.internal.zzn.zzrj(Unknown Source:147)
  at com.google.android.gms.common.internal.zze.zzs(Unknown Source:47)
  at com.google.android.gms.common.internal.zzi.zzrk(Unknown Source:54)
  at com.google.android.gms.common.internal.zzh.handleMessage(Unknown Source:275)
  at android.os.Handler.dispatchMessage(Handler.java:105)
  at android.os.Looper.loop(Looper.java:164)
  at android.app.ActivityThread.main(ActivityThread.java:6548)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Running application "eBikes" with appParams: {"rootTag":1}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
{ currentUser: {},
  currentLocation: { lat: 0, lon: 0 },
  currentQRCode: { qrcode: '' },
  currentLocationStatus: { status: false } }
main.js
'Splash check location: ', 'undetermined'
Splash: requestPermission
```

Code:
```
componentWillMount() {
    Permissions.check('location')
      .then(response => {
        //response is one of: 'authorized', 'denied', 'restricted', or 'undetermined'
        console.log('Splash check location: ', response);
        this.setState({ locationPermission: response })
        if (response !== 'authorized') this._requestPermission();
        // else this.getLocation();
      });
}
_requestPermission = () => {
    console.log("Splash: requestPermission");
    Permissions.request('location')
      .then(response => {
        console.log("Splash request location: ", response);
        this.setState({ locationPermission: response })
      });
}
```

AndroidManifest:
```
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
<uses-permission android:name="android.permission.VIBRATE" />
```

dependencies
```
    "ac-qrcode": "^1.0.1",
    "axios": "^0.16.2",
    "events": "^1.1.1",
    "fs-": "^1.0.0",
    "moment": "^2.19.2",
    "native-base": "^2.3.9",
    "react": "16.0.0-alpha.12",
    "react-native": "0.48.4",
    "react-native-action-button": "^2.8.4",
    "react-native-android-location-services-dialog-box": "^2.4.4",
    "react-native-android-settings-library": "^1.0.3",
    "react-native-camera": "^0.10.0",
    "react-native-datepicker": "^1.6.0",
    "react-native-fcm": "^13.1.0",
    "react-native-fs": "^2.9.11",
    "react-native-google-location": "^0.2.0",
    "react-native-htmlview": "^0.12.1",
    "react-native-image-picker": "^0.26.7",
    "react-native-image-placeholder": "^1.0.14",
    "react-native-location": "git+https://github.com/timfpark/react-native-location.git#master",
    "react-native-maps": "^0.20.1",
    "react-native-permissions": "^1.1.1",
    "react-native-render-html": "^3.9.0",
    "react-native-scrollable-tab-view": "^0.6.7",
    "react-native-swiper": "^1.5.13",
    "react-native-ultimate-listview": "^3.3.0",
    "react-navigation": "^1.2.0",
    "react-redux": "^5.0.7",
    "redux": "^3.7.2",
    "redux-logger": "^3.0.6",
    "redux-saga": "^0.15.4"
```

**Comment by vikrantnegi** [comment]
Same issue here. Please suggest a solution. Thanks.

**Comment by abhideepmallick** [comment]
Anything on this yet?

**Comment by chocnut** [comment]
this is also an issue to me I'm using react native 0.55

**Comment by pnthach95** [comment]
Finally I found the reason. `react-native-google-location` is outdated, it causes crashing on Android 6 and above.
If you're using `react-native-google-location`, open `/node_modules/react-native-google-location/android/app/src/main/java/com/timhagn/rngloc/LocationProvider.java` and edit:
```
//import this at top of file
import android.content.pm.PackageManager;
import android.support.v4.app.ActivityCompat;
...

    @Override
    public void onConnected(Bundle bundle) {
        Log.i(TAG, "Location services connected.");

// ADD THIS TO FIX
	if (ActivityCompat.checkSelfPermission(mContext, android.Manifest.permission.ACCESS_FINE_LOCATION) != PackageManager.PERMISSION_GRANTED && ActivityCompat.checkSelfPermission(mContext, android.Manifest.permission.ACCESS_COARSE_LOCATION) != PackageManager.PERMISSION_GRANTED) {
            Log.d("Location", "Return");
            return;
        }
// ADD THIS TO FIX

        // We are Connected!
        connected = true;
        // First, get Last Location and return it to Callback
        Location location = LocationServices.FusedLocationApi.getLastLocation(mGoogleApiClient);
        if (location != null) {
            mLocationCallback.handleNewLocation(location);
        }
        // Now request continuous Location Updates
        LocationServices.FusedLocationApi.requestLocationUpdates(mGoogleApiClient, mLocationRequest, this);
    }
```

If you don't, check logcat to see what dependency cause problem.
Close issue.

**Comment by isener** [comment]
@pnthach95 yes It works after I add permission check line to react-native-google-location package. Thanks@@!!
