### ISSUE TITLE
@providesModule naming collision error after installing 

### ISSUE THREAD

**Issue by frangeris** [zoontek/react-native-permissions#290]
Here's the console log, do you have any suggestions to take action from here?

```
warning: the transform cache was reset.
Loading dependency graph...(node:70265) UnhandledPromiseRejectionWarning: Error: jest-haste-map: @providesModule naming collision:
  Duplicate module name: react-native
  Paths: /Users/frang/code/myapp/ios/Pods/React/package.json collides with /Users/frang/code/myapp/node_modules/react-native/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
    at setModule (/Users/frang/code/myapp/node_modules/jest-haste-map/build/index.js:462:17)
    at workerReply (/Users/frang/code/myapp/node_modules/jest-haste-map/build/index.js:512:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:70265) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:70265) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:70265) UnhandledPromiseRejectionWarning: Error: jest-haste-map: @providesModule naming collision:
  Duplicate module name: react-native
  Paths: /Users/frang/code/myapp/ios/Pods/React/package.json collides with /Users/frang/code/myapp/node_modules/react-native/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
    at setModule (/Users/frang/code/myapp/node_modules/jest-haste-map/build/index.js:462:17)
    at workerReply (/Users/frang/code/myapp/node_modules/jest-haste-map/build/index.js:512:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:70265) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```

### Describe your environment

* React-Native version: `    "react-native": "^0.57.8",`
* Platform: iOS, Android, both? `iOS`
* Device (which one?), simulator? `simulator`
* OS version `macOS High Sierra 10.13.6`
* react-native-permissions version `"^1.1.1",`
* Devtools: Xcode? Android Studio version? `Xcode`
* (Android only: buildToolsVersion)

### How to repeat issue and example

Fresh install and run on iOS

**Comment by LorandP** [comment]
I also have this problem, the only way I could solve this was by adding the library manually.

**Comment by zoontek** [comment]
I am closing this since this issue does not exists anymore with the [2.0.0 release](https://github.com/react-native-community/react-native-permissions/releases/tag/2.0.0).
