### ISSUE TITLE
android app crash when permission denied.

### ISSUE THREAD

**Issue by roshans1307** [zoontek/react-native-permissions#602]
# Bug report
021-05-11 16:49:13.423 8874-8874/com.variis.mobile.dev E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.variis.mobile.dev, PID: 8874
    java.lang.RuntimeException: Unable to resume activity {com.variis.mobile.dev/com.variis.mobile.MainActivity}: java.lang.NullPointerException: Attempt to read from field 'com.facebook.react.bridge.Callback com.zoontek.rnpermissions.RNPermissionsModule$Request.callback' on a null object reference
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4759)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4797)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:187)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:102)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2294)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:254)
        at android.app.ActivityThread.main(ActivityThread.java:8215)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
     Caused by: java.lang.NullPointerException: Attempt to read from field 'com.facebook.react.bridge.Callback com.zoontek.rnpermissions.RNPermissionsModule$Request.callback' on a null object reference
        at com.zoontek.rnpermissions.RNPermissionsModule.onRequestPermissionsResult(RNPermissionsModule.java:402)
        at com.facebook.react.ReactActivityDelegate$2.invoke(ReactActivityDelegate.java:171)
        at com.facebook.react.ReactActivityDelegate.onResume(ReactActivityDelegate.java:102)
        at com.facebook.react.GoogleCastActivity.onResume(GoogleCastActivity.java:66)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1457)
        at android.app.Activity.performResume(Activity.java:8289)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4749)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4797) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:187) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:102) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2294) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:254) 
        at android.app.ActivityThread.main(ActivityThread.java:8215) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006) 
2021-05-11 16:49:13.450 8874-8874/com.variis.mobile.dev I/Sentry: Not possible to read external files directory
2021-05-11 16:49:13.521 8874-8874/com.variis.mobile.dev I/Process: Sending signal. PID: 8874 SIG: 9

## Environment info

`react-native info` output:

```bash
# paste it here
```

Library version: x.x.x

## Steps to reproduce

1. …
2. …

Describe what you expected to happen:

1. … if permission denied then provide denied status
2. …

## Reproducible sample code

for now added temp patch : 

/node_modules/react-native-permissions/android/src/main/java/com/zoontek/rnpermissions/RNPermissionsModule.java

 @Override
  public boolean onRequestPermissionsResult(int requestCode, String[] permissions, int[] grantResults) {
    try {
      Request request = mRequests.get(requestCode);
      request.callback.invoke(grantResults, getPermissionAwareActivity(), request.rationaleStatuses);
      mRequests.remove(requestCode);
      return mRequests.size() == 0;
    }catch (NullPointerException e){
      return false;
    }
  }

**Comment by zoontek** [comment]
Please submit an issue with formatted code, JS reproduction code and properly filled informations (Device, OS version, library version, etc)

**Comment by kkureli** [comment]
> # Bug report
> 021-05-11 16:49:13.423 8874-8874/com.variis.mobile.dev E/AndroidRuntime: FATAL EXCEPTION: main
> Process: com.variis.mobile.dev, PID: 8874
> java.lang.RuntimeException: Unable to resume activity {com.variis.mobile.dev/com.variis.mobile.MainActivity}: java.lang.NullPointerException: Attempt to read from field 'com.facebook.react.bridge.Callback com.zoontek.rnpermissions.RNPermissionsModule$Request.callback' on a null object reference
> at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4759)
> at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4797)
> at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
> at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:187)
> at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:102)
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2294)
> at android.os.Handler.dispatchMessage(Handler.java:106)
> at android.os.Looper.loop(Looper.java:254)
> at android.app.ActivityThread.main(ActivityThread.java:8215)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
> Caused by: java.lang.NullPointerException: Attempt to read from field 'com.facebook.react.bridge.Callback com.zoontek.rnpermissions.RNPermissionsModule$Request.callback' on a null object reference
> at com.zoontek.rnpermissions.RNPermissionsModule.onRequestPermissionsResult(RNPermissionsModule.java:402)
> at com.facebook.react.ReactActivityDelegate$2.invoke(ReactActivityDelegate.java:171)
> at com.facebook.react.ReactActivityDelegate.onResume(ReactActivityDelegate.java:102)
> at com.facebook.react.GoogleCastActivity.onResume(GoogleCastActivity.java:66)
> at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1457)
> at android.app.Activity.performResume(Activity.java:8289)
> at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4749)
> at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4797) 
> at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52) 
> at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:187) 
> at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:102) 
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2294) 
> at android.os.Handler.dispatchMessage(Handler.java:106) 
> at android.os.Looper.loop(Looper.java:254) 
> at android.app.ActivityThread.main(ActivityThread.java:8215) 
> at java.lang.reflect.Method.invoke(Native Method) 
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612) 
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006) 
> 2021-05-11 16:49:13.450 8874-8874/com.variis.mobile.dev I/Sentry: Not possible to read external files directory
> 2021-05-11 16:49:13.521 8874-8874/com.variis.mobile.dev I/Process: Sending signal. PID: 8874 SIG: 9
> 
> ## Summary
> ## Environment info
> `react-native info` output:
> 
> ```shell
> # paste it here
> ```
> 
> Library version: x.x.x
> 
> ## Steps to reproduce
> 1. …
> 2. …
> 
> Describe what you expected to happen:
> 
> 1. … if permission denied then provide denied status
> 2. …
> 
> ## Reproducible sample code
> for now added temp patch :
> 
> /node_modules/react-native-permissions/android/src/main/java/com/zoontek/rnpermissions/RNPermissionsModule.java
> 
> @Override
> public boolean onRequestPermissionsResult(int requestCode, String[] permissions, int[] grantResults) {
> try {
> Request request = mRequests.get(requestCode);
> request.callback.invoke(grantResults, getPermissionAwareActivity(), request.rationaleStatuses);
> mRequests.remove(requestCode);
> return mRequests.size() == 0;
> }catch (NullPointerException e){
> return false;
> }
> }

can u solve?

**Comment by mikehardy** [comment]
@kkureli this the equivalent of spam:

> can u solve?

You must read and put in some effort. 

> Please submit an issue with formatted code, JS reproduction code and properly filled informations (Device, OS version, library version, etc)

Spam is unwanted because it is effectively the theft of people's time. That's what you have done here, please don't do that.

**Comment by frankbolviken** [comment]
I'm getting this error now on some devices :/
