### ISSUE TITLE
App crash after permission denied in android

### ISSUE THREAD

**Issue by roshanEquinox** [zoontek/react-native-permissions#605]
# Bug report

## Summary
This error is occurred in the app whenever location permission is denied in android

java.lang.NullPointerException: Attempt to read from field 'com.facebook.react.bridge.Callback  com.zoontek.rnpermissions.RNPermissionsModule$Request.callback' on a null object reference

## Environment info

Library version:
 "react": "16.13.1",
  "react-native": "0.63.4",
   "react-native-permissions": "^3.0.1",

```bash
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 30.82 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.23.3 - ~/.config/nvm/versions/node/v10.23.3/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/.config/nvm/versions/node/v10.23.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /Users/roshans/.rvm/gems/ruby-2.6.3/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 23, 25, 26, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.1
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_275 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: ^4.14.0 => 4.14.0 
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 3.0.1

## Steps to reproduce

1. Ask for location permission in android
2. Deny the permission when permission popup is showed up

Describe what you expected to happen:

1. App should not crash after clicking on deny option

## Reproducible sample code

          export const getPermission = async (
            permission: Permission,
          ): Promise<boolean> => {
            const result: PermissionStatus = await check(permission);
          
            if (result === RESULTS.UNAVAILABLE || result === RESULTS.BLOCKED) {
              return false;
            }
          
            if (result === RESULTS.LIMITED || result === RESULTS.GRANTED) {
              return true;
            }
          
            if (result === RESULTS.DENIED) {
              const requestResult: PermissionStatus = await request(permission);
          
              return requestResult === RESULTS.GRANTED;
            }
          
            return false;
          };

Current Solution applied : 

for now added temp patch :

/node_modules/react-native-permissions/android/src/main/java/com/zoontek/rnpermissions/RNPermissionsModule.java

```java

      @override
      public boolean onRequestPermissionsResult(int requestCode, String[] permissions, int[] grantResults) {
          try {
              Request request = mRequests.get(requestCode);
              request.callback.invoke(grantResults, getPermissionAwareActivity(), request.rationaleStatuses);
              mRequests.remove(requestCode);
              return mRequests.size() == 0;
          } catch (NullPointerException e) {
              return false;
          }
      }

**Comment by zoontek** [comment]
@roshanEquinox Which permission do you request? Your sample code does not contain it.

PERMISSIONS.ANDROID.???

**Comment by zoontek** [comment]
@roshanEquinox I could not reproduce it. Maybe you tried requesting `ACCESS_BACKGROUND_LOCATION`?

**Comment by xgenem** [comment]
Permissions granted or denied. It crashed.

**Comment by xgenem** [comment]
Can confirm it is due to missing permissions in AndroidManifest

**Comment by xgenem** [comment]
Hmmm. Unfortunately. Crash still happened :'(

```
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.bridge.Callback.invoke(java.lang.Object[])' on a null object reference
        at com.facebook.react.modules.permissions.PermissionsModule.onRequestPermissionsResult(PermissionsModule.java:207)
```

**Comment by sonnd08** [comment]
Same issue, crash the first time permission granted

My manifest permission
```
<uses-permission android:name="android.permission.INTERNET" />
  <uses-permission android:name="android.permission.VIBRATE"/>
  <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
  <uses-permission android:name="android.permission.RECORD_AUDIO" />
  ```

**Comment by puskin** [comment]
The issue is still present for me. Version 3.2.0 of the module.

**Comment by mikehardy** [comment]
@puskin94 to confirm, you have the exact same message - no differences at all - from https://github.com/zoontek/react-native-permissions/issues/605#issuecomment-886553554 ?

**Comment by puskin** [comment]
> @puskin94 to confirm, you have the exact same message - no differences at all - from [#605 (comment)](https://github.com/zoontek/react-native-permissions/issues/605#issuecomment-886553554) ?

@mikehardy correct! same exact crash with same stacktrace

**Comment by zoontek** [comment]
@puskin94 Maybe you can provide more context for a viable reproduction? Thanks (cf https://github.com/zoontek/react-native-permissions/issues/605#issuecomment-841787063)

**Comment by puskin** [comment]
@zoontek 

- platform: Android 12
- react-native version: 0.68.0

rn code (partially edited):

```js
        await request(PERMISSIONS.ANDROID.ACCESS_COARSE_LOCATION);
        await request(PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION);
        await check(PERMISSIONS.ANDROID.ACCESS_COARSE_LOCATION);
        await check(PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION);
```

same exact error message as mentioned before when denying the location permission

**Comment by zoontek** [comment]
@puskin94 Location permissions should be requested at the same time as it's the same prompt.

```ts
await requestMultiple([PERMISSIONS.ANDROID.ACCESS_COARSE_LOCATION, PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION])
```

**Comment by puskin** [comment]
@zoontek thanks for the super quick answer, but I just tried and that does not solve the issue

**Comment by puskin** [comment]
@zoontek @mikehardy  funny enough, the proposed "patch" seems to not be working anymore. The crash is happening now on the react-native package, in the PermissionsAndroid module:

![image](https://user-images.githubusercontent.com/8344987/165723393-4c8429c1-4296-4077-80a5-ea4e147e2c60.png)


```java
2022-04-28 13:30:50.329 10173-10173/app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: app, PID: 10173
    java.lang.RuntimeException: Unable to resume activity {app/com.app.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.bridge.Callback.invoke(java.lang.Object[])' on a null object reference
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4757)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4790)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
        at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.bridge.Callback.invoke(java.lang.Object[])' on a null object reference
        at com.facebook.react.modules.permissions.PermissionsModule.onRequestPermissionsResult(PermissionsModule.java:207)
        at com.facebook.react.ReactActivityDelegate$2.invoke(ReactActivityDelegate.java:178)
        at com.facebook.react.ReactActivityDelegate.onResume(ReactActivityDelegate.java:103)
        at com.facebook.react.ReactActivity.onResume(ReactActivity.java:58)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1476)
        at android.app.Activity.performResume(Activity.java:8191)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4747)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4790) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54) 
        at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7839) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 

```

**Comment by puskin** [comment]
@zoontek @mikehardy It looks like we found the issue.

The component responsible for checking the location permission was re-rendering due to a prop changing in the redux store. This made your permissions module ask for the location permission multiple time in a very short period, thing that (we didn't know) Android does not appreciate much.

Making sure the component does not re-render in a short amount of time made android behave in the correct way

**Comment by zoontek** [comment]
@puskin94 Thanks for your investigation! I will try to add some kind of guards to avoid issues when it happens.

**Comment by puskin** [comment]
@zoontek thank you so much for your patience and the swift answers!

**Comment by alexjegor** [comment]
For me issue appeared when I've requested location and notifications permission at once. Changes in logic that now it requests permission one by one (request next only after user accepts/denies previous) helped
