### ISSUE TITLE
jest testing: waitForNextUdpate times out on checkPermissions

### ISSUE THREAD

**Issue by ItsMeJules** [zoontek/react-native-permissions#864]
### Before submitting a new issue

- [X] I tested using the latest version of the library, as the bug might be already fixed.
- [X] I tested using a [supported version](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) of react native.
- [X] I checked for possible duplicate issues, with possible answers.

### Bug summary

When testing a useEffect that's called on mount in my custom hook, the `await waitForNextUpdate` call just times out. I tried increasing timeout time but nothing changed.

### Library version

4.1.5

### Environment info

```shell
System:
    OS: macOS 14.2.1
    CPU: (11) arm64 Apple M3 Pro
    Memory: 176.20 MB / 18.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.7.1 - /usr/local/bin/node
    Yarn: 1.22.21 - /opt/homebrew/bin/yarn
    npm: 10.5.0 - /opt/homebrew/bin/npm
    Watchman: 2024.03.18.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.14.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, watchOS 10.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 2023.1 AI-231.9392.1.2311.11255304
    Xcode: 15.1/15C65 - /usr/bin/xcodebuild
  Languages:
    Java: 21.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: ^9.0.0 => 9.3.5 
    react: ^18.1.0 => 18.2.0 
    react-native: ^0.70.0 => 0.70.15 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

The issue is on the test suite. This is the tests that times out. See the waitForNextUpdate. I added a then just for debugging purposes, it doesn't change the final result.

### **Test suite**

```js
import { BatchPush } from '@batch.com/react-native-plugin';
import { useNotificationsScreen } from '@hooks/useNotificationsScreen';
import { useNavigation } from '@react-navigation/native';
import { act, renderHook } from '@testing-library/react-hooks';
import { NotificationsResponse, checkNotifications } from 'react-native-permissions';

jest.mock('@react-navigation/native', () => ({
  useNavigation: jest.fn(),
}));

jest.mock('react-native-permissions', () => ({
  checkNotifications: jest.fn(),
}));

jest.mock('@batch.com/react-native-plugin', () => ({
  BatchPush: {
    requestNotificationAuthorization: jest.fn(),
  },
}));

describe('useNotificationsScreen', () => {
  afterEach(() => {
    jest.clearAllMocks();
  });
  it('should check notifications permission on mount', async () => {
    jest.mocked(checkNotifications).mockResolvedValue({
      status: 'granted',
      settings: {},
    } as NotificationsResponse);

    const { result, waitForNextUpdate } = renderHook(() => useNotificationsScreen());

    await waitForNextUpdate().then(() => {
      console.log('waitForNextUpdate');
    });

    expect(checkNotifications).toHaveBeenCalled();
    expect(result.current.notificationsEnabled).toBe(true);
  });
```
  
### **Test logs**
```js
FAIL  src/hooks/__tests__/useNotificationScreen.test.ts
  useNotificationsScreen
    ✕ should check notifications permission on mount (1018 ms)
    ○ skipped should navigate to Notifications screen
    ○ skipped should request notifications permission

  ● useNotificationsScreen › should check notifications permission on mount

    Timed out in waitForNextUpdate after 1000ms.

      31 |     const { result, waitForNextUpdate } = renderHook(() => useNotificationsScreen());
      32 |
    > 33 |     await waitForNextUpdate().then(() => {
         |     ^
      34 |       console.log('waitForNextUpdate');
      35 |     });
      36 |

      at waitForNextUpdate (node_modules/@testing-library/react-hooks/lib/core/asyncUtils.js:96:13)
      at Object.<anonymous> (src/hooks/__tests__/useNotificationScreen.test.ts:33:5)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 2 skipped, 3 total
```

### Reproducible sample code

```js
export const useNotificationsScreen = () => {
  const { navigate } = useNavigation<NavigationScreenProp<any, any>>();
  const [notificationsEnabled, setNotificationsEnabled] = useState(false);

  useEffect(() => {
    (async () => {
      const { status } = await checkNotifications();
      setNotificationsEnabled(status === 'granted');
    })();
  }, []);
...
}
```

**Comment by zoontek** [comment]
@ItsMeJules What mock are you using? Are you sure it actually trigger a re-render?

**Comment by ItsMeJules** [comment]
@zoontek All the mocked implementations are provided in the sample code. Or else I didn't understand your question. I am, when working on the feature, it was re-setting the state and re-rendering my components based on the return value of the custom hook.

**Comment by zoontek** [comment]
@ItsMeJules Yes, I saw it after. It was poorly formatted and unreadable at first.
First, try to use the repository mock: https://github.com/zoontek/react-native-permissions/blob/master/mock.js

**Comment by zoontek** [comment]
Reading your code, it's normal, no issue here.
You are using this as a mock:

```ts
jest.mock('react-native-permissions', () => ({
  checkNotifications: jest.fn(), // ⚠️ sync function, returns void (undefined)
}));
```

Except you should use this:

```ts
jest.mock('react-native-permissions', () => ({
  checkNotifications: jest.fn(async () => ({ status: "granted" })),
}));
```

Then this:

```ts
export const useNotificationsScreen = () => {
  const { navigate } = useNavigation<NavigationScreenProp<any, any>>();
  const [notificationsEnabled, setNotificationsEnabled] = useState(false);

  useEffect(() => {
    (async () => {
      const { status } = await checkNotifications(); // will return undefined, and crash as it cannot be destructured
      setNotificationsEnabled(status === 'granted'); // never fired
    })();
  }, []);
...
}
```
PS: There's a "Testing with Jest" part in the README that help to setup the mock: https://github.com/zoontek/react-native-permissions?tab=readme-ov-file#testing-with-jest

**Comment by ItsMeJules** [comment]
@zoontek I have it mocked in my `jest-stup.ts` file. As so :
```ts
jest.mock('react-native-permissions', () => require('react-native-permissions/mock'));
```

This is how I call my `jest-setup.ts` config file in my `jest.config.js`
```js
  setupFilesAfterEnv: ['<rootDir>/jest-setup.ts'],
```

_I did read the testing with jest part in the README.md and found it a little scarce._

Applying your latest edited reply, I still have the same issue.

```ts
jest.mock('react-native-permissions', () => ({
  checkNotifications: jest.fn(async () => ({ status: 'granted' })),
}));

describe('useNotificationsScreen', () => {
  afterEach(() => {
    jest.clearAllMocks();
  });
  it('should check notifications permission on mount', async () => {
    jest.mocked(checkNotifications).mockResolvedValue({
      status: 'granted',
      settings: {},
    } as NotificationsResponse); // <- I also tried removing this whole line and still timed out.

    const { result, waitForNextUpdate } = renderHook(() => useNotificationsScreen());

    await waitForNextUpdate().then(() => {
      console.log('waitForNextUpdate');
    });

    expect(checkNotifications).toHaveBeenCalled();
    expect(result.current.notificationsEnabled).toBe(true);
  });
  ```

**Comment by zoontek** [comment]
@ItsMeJules Create a repository with this, I will check / fix it.

**Comment by ItsMeJules** [comment]
I think I found the issue. I had to wrap the waitForNextUpdate into an act just after rendering the component. As there's a state update on mount.

```ts
  it('should check notifications permission on mount', async () => {
    const { result, waitForNextUpdate } = renderHook(() => useNotificationsScreen());

    await act(async () => {
      await waitForNextUpdate();
    });

    expect(checkNotifications).toHaveBeenCalled();
    expect(result.current.notificationsEnabled).toBe(true);
  });
```

**Comment by zoontek** [comment]
Good to know, I'm closing this.
