### ISSUE TITLE
[5.0.0] Parameter specified as non-null is null: method com.zoontek.rnpermissions.RNPermissionsModule.check

### ISSUE THREAD

**Issue by efstathiosntonas** [zoontek/react-native-permissions#898]
### Before submitting a new issue

- [X] I tested using the latest version of the library, as the bug might be already fixed.
- [X] I tested using a [supported version](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) of react native.
- [X] I checked for possible duplicate issues, with possible answers.

### Bug summary

After upgrading to v5 I get this error on rn 0.75.4 Paper:

```
Exception in native call (Ask Gemini)
  java.lang.NullPointerException: Parameter specified as non-null is null: method com.zoontek.rnpermissions.RNPermissionsModule.check, parameter permission
   at com.zoontek.rnpermissions.RNPermissionsModule.check(Unknown Source:2)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
   at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:146)
   at com.facebook.jni.NativeRunnable.run(Native Method)
   at android.os.Handler.handleCallback(Handler.java:958)
   at android.os.Handler.dispatchMessage(Handler.java:99)
   at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
   at android.os.Looper.loopOnce(Looper.java:205)
   at android.os.Looper.loop(Looper.java:294)
   at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:235)
   at java.lang.Thread.run(Thread.java:1012)
```

### Library version

5.0.0

### Environment info

```shell
System:
  OS: macOS 15.0.1
  CPU: (20) arm64 Apple M1 Ultra
  Memory: 491.69 MB / 64.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.17.0
    path: ~/.nvm/versions/node/v20.17.0/bin/node
  Yarn:
    version: 4.4.1
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.9.0
    path: ~/.nvm/versions/node/v20.17.0/bin/npm
  Watchman:
    version: 2024.10.07.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/stathis/.gem/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.0
      - iOS 18.0
      - macOS 15.0
      - tvOS 18.0
      - visionOS 2.0
      - watchOS 11.0
  Android SDK:
    API Levels:
      - "31"
      - "33"
      - "34"
    Build Tools:
      - 30.0.3
      - 33.0.0
      - 33.0.1
      - 33.0.2
      - 34.0.0
    System Images:
      - android-25 | Google APIs ARM 64 v8a
      - android-27 | Google APIs ARM 64 v8a
      - android-28 | Google APIs ARM 64 v8a
      - android-29 | Google APIs ARM 64 v8a
      - android-30 | Google APIs ARM 64 v8a
      - android-31 | Google APIs ARM 64 v8a
      - android-33 | Google APIs ARM 64 v8a
      - android-34 | Google APIs ARM 64 v8a
      - android-34 | Google Play ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.19072.14.2412.12360217
  Xcode:
    version: 16.0/16A242d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.12
    path: /usr/bin/javac
  Ruby:
    version: 3.3.5
    path: /opt/homebrew/opt/ruby/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Steps to reproduce

1. install version 5.0.0
2. build on on android

### Reproducible sample code

```js
Just simple permissions check.
```

**Comment by efstathiosntonas** [comment]
After running a `tsc` check, it seems that `PERMISSIONS.ANDROID.POST_NOTIFICATIONS` is missing on v5.0.0:

```tsx
 check(PERMISSIONS.ANDROID.POST_NOTIFICATIONS)
            .then((result) => {
              if (result === RESULTS.GRANTED) {
                setHasPermission(true);
              } else {
                setHasPermission(false);
              }
              setLoading(false);
            })
            .catch();
```

Is this a bug or intentional? 🤔 

edit: On README it exists so I guess it's a bug.

**Comment by zoontek** [comment]
@efstathiosntonas Yes.

`checkNotifications` / `requestNotifications` is the way to go: works on all platforms, is able to check if notications are enabled on Android < 13. Now that `requestNotifications` accept a `rationale`, there's no reason to use `PERMISSIONS.ANDROID.POST_NOTIFICATIONS` directly.

**Comment by efstathiosntonas** [comment]
@zoontek perfect, let's close this.

**Comment by zoontek** [comment]
> edit: On README it exists so I guess it's a bug.

it exists in so you can specify it in your `AndroidManifest.xml`, but is not in this list anymore:

<img width="493" alt="Screenshot 2024-10-13 at 10 47 40" src="https://github.com/user-attachments/assets/8d256beb-3ad0-4caf-9433-a0cc68af36b9">
